load("//bazel/qt:qt.bzl", "qt_cc_binary")

package(default_visibility = ["//visibility:public"])

# Main PAM helper
qt_cc_binary(
    name = "gxdm-helper",
    srcs = [
        "Backend.cpp",
        "HelperApp.cpp",
        "UserSession.cpp",
        "backend/PamBackend.cpp",
        "backend/PamHandle.cpp",
    ] + glob([
        "*.h",
        "backend/*.h",
    ]),
    includes = [
        ".",
        "backend",
    ],
    linkopts = [
        "-lpam",
        "-lpam_misc",
        "-lXau",
    ],
    moc_hdrs = [
        "Backend.h",
        "HelperApp.h",
        "UserSession.h",
        "backend/PamBackend.h",
    ],
    deps = [
        "//src/auth:auth",
        "//src/common:common",
    ],
)

# Wayland session launcher.
qt_cc_binary(
    name = "gxdm-helper-start-wayland",
    srcs = [
        "HelperStartWayland.cpp",
        "waylandhelper.cpp",
        "waylandsocketwatcher.cpp",
    ] + glob(["*.h"]),
    moc_hdrs = [
        "waylandhelper.h",
        "waylandsocketwatcher.h",
    ],
    deps = [
        "//src/auth:auth",
        "//src/common:common",
    ],
)

# X11 session launcher.
qt_cc_binary(
    name = "gxdm-helper-start-x11user",
    srcs = [
        "HelperStartX11User.cpp",
        "xorguserhelper.cpp",
    ] + glob(["*.h"]),
    linkopts = ["-lXau"],
    moc_hdrs = ["xorguserhelper.h"],
    deps = ["//src/common:common"],
)
