#!/bin/sh
set -e

DEFAULT_DISPLAY_MANAGER_FILE=/etc/X11/default-display-manager
DEFAULT_SERVICE=/etc/systemd/system/display-manager.service

case "$1" in
    purge)
        if [ -d /var/lib/gxdm ]; then rm -r /var/lib/gxdm; fi
        if [ -d /run/gxdm ];     then rm -r /run/gxdm;     fi
        if [ -f /var/log/gxdm.log ]; then rm /var/log/gxdm.log; fi

        if getent passwd gxdm >/dev/null; then
            if command -v deluser >/dev/null; then
                deluser --system gxdm >&2 || echo "Could not remove gxdm user." >&2
            fi
        fi
        if getent group gxdm >/dev/null; then
            if command -v delgroup >/dev/null; then
                delgroup --system gxdm >&2 || echo "Could not remove gxdm group." >&2
            fi
        fi

        # A dangling display-manager.service means no other DM took over.
        if [ ! -e "$DEFAULT_DISPLAY_MANAGER_FILE" ] &&
           [ -h "$DEFAULT_SERVICE" ] && [ ! -e "$DEFAULT_SERVICE" ]; then
            rm "$DEFAULT_SERVICE"
        fi
        ;;
    abort-install|abort-upgrade)
        # roll back displacement of default display manager file
        if [ -e "$DEFAULT_DISPLAY_MANAGER_FILE.dpkg-tmp" ]; then
            mv "$DEFAULT_DISPLAY_MANAGER_FILE.dpkg-tmp" \
               "$DEFAULT_DISPLAY_MANAGER_FILE"
        fi
        ;;
esac

#DEBHELPER#

exit 0
